Repository tenzin1308/BudgetIt_2.0, pull requests merged in 2022-01, with the labels that each got.

#9 feat: implemented BJs Vegetables scraper script
  server/python/BJs_Vegetables.py
  server/routers/budgetItRouter.js
Labels: enhancement, script, BJs

#10 feat: implemented BJs Fruits scraper script
  server/python/BJs_Fruits.py
Labels: enhancement, script, BJs

#11 build: implemented python script to scrape fruits from target
  server/python/Target_Fruits.py
Labels: enhancement, build

#15 fix: fixed target fruits script, implemented general script to run al…
  server/python/BJs_Fruits.py
  server/python/BJs_Vegetables.py
  server/python/Target_Fruits.py
  server/python/Target_Vegetables.py
  server/python/main.py
Labels: script, fix, Target

#18 Tenzin skeleton integration
  client/package-lock.json
  client/src/components/Cards.js
  client/src/components/GroupSearch.js
  client/src/components/NavBar.js
  client/src/pages/Home.js
  server/package-lock.json
  server/routers/budgetItRouter.js
Labels: enhancement

#19 doc: Made changes to README
  README.md
Labels: documentation

#21 Justin styling
  client/src/App.js
  client/src/components/Cards.js
  client/src/components/GeneralLayout.js
  client/src/components/GroupSearch.js
  client/src/components/NavBar.js
  client/src/pages/About.js
  client/src/pages/Home.js
  client/src/pages/Products.js
Labels: style

#24 Tenzin deploy
  client/package.json
  client/src/pages/Home.js
  package-lock.json
  server/package.json
  server/server.js
Labels: build, deployment

#22 fix: Item display on home page
  client/src/pages/Home.js
  package-lock.json
Labels: fix, debug

#30 Tenzin fix
  client/package.json
  client/src/App.js
  client/src/components/Cards.js
  client/src/components/GeneralLayout.js
  client/src/pages/About.js
  client/src/pages/Home.js
Labels: enhancement
